# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

### 관리자의 예약 조회
GET http://127.0.0.1:8000/reservations
Authorization: Bearer admin
Accept: application/json

### id가 2번인 사용자의 예약 조회
GET http://127.0.0.1:8000/reservations
Authorization: Bearer user2
Accept: application/json

### id가 2번인 사용자의 가능한 예약 시간 조회
GET http://localhost:8000/exam-schedules/available
Authorization: user2

### 일반 사용자로 예약 생성
POST http://localhost:8000/reservations
Authorization: user2
Content-Type: application/json

{
    "start_time": "2025-04-24T14:00:00",
    "end_time": "2025-04-24T16:00:00",
    "requested_seats": 20000
}

### 관리자로 예약 확인
PATCH http://localhost:8000/reservations/2/confirm
Authorization: admin
Content-Type: application/json

### 사용자가 본인의 미확정 예약 수정
PATCH http://localhost:8000/reservations/4
Authorization: user2
Content-Type: application/json

{
    "requested_seats": 10000
}

### 예약 삭제 - 관리자
DELETE http://localhost:8000/reservations/1
Authorization: admin

### 예약 삭제 - 일반 사용자
DELETE http://localhost:8000/reservations/1
Authorization: user1